### ISSUE TITLE
Can not disable git status

### ISSUE THREAD

**Issue by jaypikay** [janoamaral/tokyo-night-tmux#106]
https://github.com/janoamaral/tokyo-night-tmux/blob/b45b742eb3fdc01983c21b1763594b549124d065/src/git-status.sh#L3
https://github.com/janoamaral/tokyo-night-tmux/blob/b45b742eb3fdc01983c21b1763594b549124d065/src/git-status.sh#L4

Should it not something like SHOW_GIT?

**Comment by janoamaral** [comment]
Hi @jaypikay, it's a misnaming of the variable, but the assignment checks for the correct variable `tokyo-night-tmux_show_git`

https://github.com/janoamaral/tokyo-night-tmux/blob/b45b742eb3fdc01983c21b1763594b549124d065/src/git-status.sh#L3

It should work without problem.
