### ISSUE TITLE
status bar color changed to green after new changes

### ISSUE THREAD

**Issue by al3rez** [janoamaral/tokyo-night-tmux#14]
hi Jano

I've been using your theme and I love it but it suddenly status bar turned green after I updated plugins using tpm.

**Comment by al3rez** [comment]
![Screenshot from 2023-12-15 10-31-02](https://github.com/janoamaral/tokyo-night-tmux/assets/15009059/937f42cc-2184-4c0e-8f90-af868faeabdb)

**Comment by al3rez** [comment]
it works fine on mac os though

**Comment by janoamaral** [comment]
Hi, sorry for the inconvenience, please confirm fix. It should work fine now.

**Comment by al3rez** [comment]
sweet! works great.

**Comment by al3rez** [comment]
> Hi, sorry for the inconvenience, please confirm fix. It should work fine now.

amazing work!
