### ISSUE TITLE
I setup but the icon at the bottom bar seem to be broken

### ISSUE THREAD

**Issue by pisarnwate** [janoamaral/tokyo-night-tmux#21]
![image](https://github.com/janoamaral/tokyo-night-tmux/assets/113778538/e01958be-7659-44f5-939d-c4870610dd60)

as per above picture.  I setup but the icon at the bottom bar seem to be broken.

It could be my fault, not the issue.  But it might be useful for anyone who encounter the same problem.

**Comment by janoamaral** [comment]
Hi, you need to use a nerd font for this to work. You can check this to know more about https://www.nerdfonts.com/#home
