### ISSUE TITLE
How to get noto font working on osx/mac?

### ISSUE THREAD

**Issue by mxaddict** [janoamaral/tokyo-night-tmux#36]
Can't seem to get the default terminal.app and kitty.app to detect noto font for use with tmux.

Is there a way to disable the use of notofont for the numbers in the bottom?

Or is there a procedure to install noto font properly on a mac?

I have this exact same theme used on my arch install, and the font is working properly, so I believe it's a mac thing that I need to figure out how to use the font properly.

**Comment by janoamaral** [comment]
Which numbers are not working? Can you share a screenshot to see the issue?

**Comment by mxaddict** [comment]
The number indicator for the tmux tabs.

Cheers,
Barry Deeney

**Comment by mxaddict** [comment]
On arch, I see this: 
![image](https://github.com/janoamaral/tokyo-night-tmux/assets/1060905/8165e734-fb57-4b44-8b28-c24ec2f51b7d)

**Comment by mxaddict** [comment]
On OSX, I see this:

<img width="357" alt="Screenshot 2024-01-23 at 1 23 46 PM" src="https://github.com/janoamaral/tokyo-night-tmux/assets/1060905/7a1fbf55-d9cc-4711-8dc0-efa06dd5ad9e">

**Comment by Patricus** [comment]
Have a similar issue with WSL:
![image](https://github.com/janoamaral/tokyo-night-tmux/assets/23273919/0b8e0c4a-2237-4808-a4a1-56ea05f033cc)

**Comment by janoamaral** [comment]
That's odd, I believe that Noto isn't even needed. That numbers are [unicode symbols for legacy computing](https://symbl.cc/en/unicode/blocks/symbols-for-legacy-computing/#subblock-1FBF0), so any font should render normally. Using the default font of the terminal as fallback should be fine.

**Comment by Patricus** [comment]
Did some searching and the segmented digits were added in 2020 unicode 13. This is purely an OS issue and not a problem with the plugin. The OS needs to add support for these characters / update unicode.

**Comment by mxaddict** [comment]
I see, so Arch is working cause it's got updated support for unicode?

Is there a toggle to maybe use normal font for the numbers?

**Comment by Patricus** [comment]
I guess you could make a setting to toggle for the plugin, just have it default to use the unicode. So we can add something like `set -g @tokyo-night-tmux_unidigits false` in our tmux.conf.

**Comment by janoamaral** [comment]
I'll close this issue and add a new one (#37) to address this formally.

**Comment by Jarvvski** [comment]
Hey friends, I found a 'hack' to get this working on macOS, but I'm unsure about windows

I found [this discussion thread](https://github.com/ryanoasis/nerd-fonts/discussions/835) over in nerd-fonts repo

Basically, most nerd fonts are not getting this added currently. I don't know how or why it worked for you @janoamaral 😄 

Anyway, there is _a_ font from that repo that _does_ have them - `Iosevka`

I went and downloaded that, and set it up in my `kitty.conf` to be a fallback for those symbols:

```
# Font configuration
font_family      JetbrainsMono Nerd Font Mono
symbol_map U+1FBF0,U+1FBF1,U+1FBF2,U+1FBF3,U+1FBF4,U+1FBF5,U+1FBF6,U+1FBF7,U+1FBF8,U+1FBF9 Iosevka Nerd Font Mono
font_size        16.0
```

And hey presto..

![CleanShot 2024-09-22 at 20 58 50](https://github.com/user-attachments/assets/978e401e-f9ba-477e-9a58-747217bd243c)
