### ISSUE TITLE
Add number style configuration

### ISSUE THREAD

**Issue by janoamaral** [janoamaral/tokyo-night-tmux#37]
**Add users a way to configure number styles.**
Some users can not like the default styles for numbers and should be a nice feature to let them choose the style.

**Enable a plugin variable to configure styles**
We can use `@tokyo-night-tmux_window_id_style`, `@tokyo-night-tmux_pane_id_style` to select the corresponding style.

i.e.

`set -g @tokyo-night-tmux_window_id_style [style]`

The styles:
- `none`: no style
- `default`: default style from upstream
- `digital`: 7 segment number (🯰...🯹) (needs [Unicode support](https://github.com/janoamaral/tokyo-night-tmux/issues/36#issuecomment-1907072080)) 
- `roman`: roman numbers (󱂈...󱂐) (needs nerdfont)
- `fsquare`: filled square (󰎡...󰎼) (needs nerdfont)
- `hsquare`: hollow square (󰎣...󰎾) (needs nerdfont)
- `super`: superscript symbol (⁰...⁹)
- `sub`: subscript symbols (₀...₉)

**Comment by mxaddict** [comment]
Can I work on this pr?

**Comment by mxaddict** [comment]
What did you mean by this: `default: default style from upstream`

**Comment by mxaddict** [comment]
Default values are set as such:
```sh
default_window_id_style="digital"
default_pane_id_style="hsquare"
default_zoom_id_style="dsquare"
```

**Comment by guoliang** [comment]
Question on this.

I tried the new option and set the numbers with following setting
`set -g @tokyo-night-tmux_window_id_style digital`

For me the tab number is are just rectangles instead of numbers
![image](https://github.com/janoamaral/tokyo-night-tmux/assets/542598/78b81b4b-491d-455a-a477-51465a877207)

Am I missing something? I have tried few other Nerd Fonts already, with the same result
Hack Nerd Font
Noto Nerd Font
FiraCode Nerd Font

**Comment by mxaddict** [comment]
> Question on this.
> 
> I tried the new option and set the numbers with following setting `set -g @tokyo-night-tmux_window_id_style digital`
> 
> For me the tab number are just rectangles instead of numbers ![image](https://private-user-images.githubusercontent.com/542598/300532310-78b81b4b-491d-455a-a477-51465a877207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDgyNzMsIm5iZiI6MTcwNjU0Nzk3MywicGF0aCI6Ii81NDI1OTgvMzAwNTMyMzEwLTc4YjgxYjRiLTQ5MWQtNDU1YS1hNDc3LTUxNDY1YTg3NzIwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxNzA2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTRmYTgxZTgwMjVlZWZiNTNjM2U1Zjc3MDJjOGY2NjI1MWRiMmFkMTBiOGRhYThiOTEyMTVhZDBhY2Q3NjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OPp0rYbW0mRK71ABJvdWcYO7bevMXytKvHE4V70jnP8)
> 
> Am I missing something? I have tried few other Nerd Fonts already, with the same result Hack Nerd Font Noto Nerd Font FiraCode Nerd Font

Let me guess, you're on mac? 😄 

The reason this option was added was so that you can use the other formats, since `digital` one refuses to work on osx.

Check #36 for mow context.

**Comment by guoliang** [comment]
yea, I'm on mac. that's unfortunate then. I'll be using one of the other options then :|

**Comment by souravsgithub** [comment]
But I'm on ubuntu and I did everything to make it work. Still can't do it. Any suggestions guys?
