### ISSUE TITLE
Tab color does not look right

### ISSUE THREAD

**Issue by guoliang** [janoamaral/tokyo-night-tmux#38]
**Describe the issue**
![image](https://github.com/janoamaral/tokyo-night-tmux/assets/542598/4fe550cd-f224-4960-8465-2d440c5af9b5)

Tab color doesn't look right. Not sure if it has something to do with I went from gruvbox theme to tokyonight. The previous plugin is removed though.

Do you have some hint on where I can debug this?

**Environment (please complete the following information):**
- OS: [e.g. Ubuntu 20.04]: 
- terminal [e.g. kitty, alacritty]: 
- tmux version [e.g. 3.3a]: 
- tokyo-night-tmux branch [e.g. master, next, legacy]: 

**Additional context**

**Comment by janoamaral** [comment]
Do you reload tmux right?

**Comment by guoliang** [comment]
seems like my `key-binding` in tmux to reload the config doesn't work.

but I ran `killall tmux` restarted tmux instead, and now it seems to have loaded the theme, however it still doesn't look quite the same as the video you have in read me. 

the session name here for instance is cut off with one character, in the following screenshot the session name should be `personal`, and it is the same pattern with my other sessions as well.
<img width="419" alt="image" src="https://github.com/janoamaral/tokyo-night-tmux/assets/542598/5914d404-43bc-4bd0-b28d-df998675acb8">

**Comment by janoamaral** [comment]
Yeah, there is an issue open (#37) about this. Hopefully during weekend I can fix it.

**Comment by guoliang** [comment]
alright, I'll wait for it then. until then cheers
