### ISSUE TITLE
Wrong colors

### ISSUE THREAD

**Issue by dlvhdr** [janoamaral/tokyo-night-tmux#4]
After I restarted my mac, I get the wrong colors for some reason:
![image](https://user-images.githubusercontent.com/6196971/144842357-78a34792-685a-449a-9458-dce8a9aa2cdb.png)

This is my config:

```
# remap prefix from 'C-b' to 'C-a'
unbind C-b
# set-option -g prefix C-a
# bind-key C-a send-prefix
set-option -g prefix C-Space

# =============================================
# GLOBALS
# =============================================

set -g base-index 1
set -g  pane-base-index 1
set -gs escape-time 0
set -g -q mouse on
set -g mode-keys vi 
set -g history-limit 50000

# don't rename windows automatically
set-option -g allow-rename off
set-option -g renumber-windows on

# use zsh
set -g default-command "${SHELL}"
set -g default-terminal "xterm-256color"
set -g terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:sitm=\E[3m'

# theme
set -g pane-active-border-style fg=magenta

# =============================================
# BINDINGS
# =============================================

# source .tmux.conf with r
bind r source-file ~/.config/tmux/tmux.conf

# mouse support
bind -n WheelUpPane copy-mode -e
bind -n MouseDrag1Pane copy-mode -M
bind -T copy-mode-vi MouseDrag1Pane    send -X begin-selection
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-no-clear

# vim
bind-key -T copy-mode-vi Enter send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'

# ==========================================
# PLUGINS
# ==========================================

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'logico-dev/tokyo-night-tmux'

run '~/.config/tmux/plugins/tpm/tpm'

```

I'm not sure where the green color is coming from.

**Comment by AndreaOrru** [comment]
Same here.

**Comment by codenut** [comment]
i experienced the same thing too. i fixed it by setting the status bg color
`set -g status-bg #414868`

**Comment by ferrarafer** [comment]
Same here. @codenut suggestion didn't work for me.

**Comment by myusuf3** [comment]
same. any ideas @janoamaral

**Comment by betogrun** [comment]
> Same here. @codenut suggestion didn't work for me.

I was able to set the background with `set -g status-bg '#414868'`, but the colors still look strange.

![image](https://user-images.githubusercontent.com/14967395/158266948-0ab96158-8f17-4c6e-a10c-2ef708138178.png)

**Comment by betogrun** [comment]
> > Same here. @codenut suggestion didn't work for me.
> 
> I was able to set the background with `set -g status-bg '#414868'`, but the colors still look strange.
> 
> ![image](https://user-images.githubusercontent.com/14967395/158266948-0ab96158-8f17-4c6e-a10c-2ef708138178.png)

After adding the background color, I also added the [tokyo night theme for windows terminal](https://windowsterminalthemes.dev/?theme=TokyoNight), and this helped to improve the experience.

![image](https://user-images.githubusercontent.com/14967395/158484139-9cb7a83d-e19c-4757-9c6e-eef5f15f5adb.png)

**Comment by Amparose** [comment]
Better than nothing but what's in the tin is not what's shown on the label. Shame, the screenshots look really nice.

**Comment by janoamaral** [comment]
> Better than nothing but what's in the tin is not what's shown on the label. Shame, the screenshots look really nice.

The thing is I can't reproduce the bug. I'm really sorry.

**Comment by KiLLeRRaT** [comment]
I’m also getting strange colors in my terminal. My Neovim displays funky colors when viewed via tmux. I wonder if this is all a tmux setting somewhere.

**Comment by janoamaral** [comment]
> What she’ll are you all using?

ST 0.8.5 with zsh 5.9.0.1 and Tmux next-3.4

**Comment by Amparose** [comment]
I had annoying issues with colors in tmux + neovim in Alacritty (was fine in Kitty). Many solutions online didn't work for me but trial and error worked by setting this in .tmux.conf:

```
set-option -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ',xterm-256color:Tc'
```
Not sure this relates to this issue but just in case it helps.

I get the green bar with this plug in both Alacritty (0.10.1 ) and Kitty (0.25.2) in tmux 3.3a via zsh 5.8. It seems terminal colours and consistency is really hard.

**Comment by ebiscaia** [comment]
I think it is necessary to know if the terminal theme the owner of the repo is using or any modification he would have made or maybe hardcode all color in his config.

**Comment by DMunkei** [comment]
@sigugo 
Is it possible for you to post that part of your tmux.conf file? I can't seem to get it working.

**Comment by sigugo** [comment]
> @sigugo Is it possible for you to post that part of your tmux.conf file? I can't seem to get it working.

I have forked this for myself to incorporate the changes I needed, and to do some other housekeeping, the relevant part of my tmux.conf is quite minimal though.

```
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

## Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "sigugo/tokyo-night-tmux"

## Plugin Manager
run '$TMUX_CONFIG_HOME/plugins/tpm/tpm'
```
