### ISSUE TITLE
Which Noto font(s) are required for this theme?

### ISSUE THREAD

**Issue by nexxai** [janoamaral/tokyo-night-tmux#43]
The README says:

```md
## Noto Fonts

This theme requires the Noto fonts to be installed on your operating system. Make sure your 
operating system has the needed font and is configured to use one.
```

There are [207 Noto families](https://fonts.google.com/noto/fonts) so I was hoping you could narrow down which of these are required.

**Comment by janoamaral** [comment]
Noto Sans Mono should do the work. That recommendation came when we have this issue #36 open, until we found out it was an OS support.
