### ISSUE TITLE
Music Widget not showing

### ISSUE THREAD

**Issue by chetra-seng** [janoamaral/tokyo-night-tmux#51]
**Describe the issue**
Hi, I'm a beginner to tmux and I kinda have a problem setting up the music widget. I can't get it to appear in the status bar even though I followed the configuration as stated in the documentation. Did I miss anything or do I need to add more config or install something?

**To Reproduce**
Steps to reproduce the issue:
1. Followed the configuration based on doc
2. source tmux config new
3. Restart tmux-server
4. Start new tmux session

**Screenshots**
.tmux.conf
<img width="890" alt="image" src="https://github.com/janoamaral/tokyo-night-tmux/assets/62987643/9cdc3a78-4e10-4a52-a27a-0f8026451f27">
Here's my tmux
<img width="890" alt="Screenshot 2024-03-26 at 12 29 03 at night" src="https://github.com/janoamaral/tokyo-night-tmux/assets/62987643/aa3cc5d4-fbda-474a-8888-1ed334e46a0d">

**Environment (please complete the following information):**
- OS: macOS Sonoma 14.4
- terminal: Wezterm, iTerm2
- tmux version: 3.4
- tokyo-night-tmux branch: master

**Comment by janoamaral** [comment]
Hi, do you have installed [nowplaying-cli](https://github.com/kirtan-shah/nowplaying-cli)?

**Comment by janoamaral** [comment]
Also, do you installed the plugin with tpm?

**Comment by chetra-seng** [comment]
My bad, I didn't know there were 2 plugins with similar name
