### ISSUE TITLE
My status bar is yellow, and I can't see any informations on it

### ISSUE THREAD

**Issue by mtk3d** [janoamaral/tokyo-night-tmux#71]
**Describe the issue**
Since the v1.5, for default settings, my status bar became yellow, and I cannot see any text on it, it is there, but it has probably the same color as background.

**To Reproduce**
I guess, that this might be a problem of my environment

**Screenshots**
For version 1.5 and newer
<img width="855" alt="Screenshot 2024-04-15 at 23 15 02" src="https://github.com/janoamaral/tokyo-night-tmux/assets/12657846/133f8f0e-e2c4-4093-8988-b5a0e68b7b07">

For last commit before 1.5 d3d484e9bcfa22d4202f15c41d18eca7c58f0405:
<img width="852" alt="Screenshot 2024-04-15 at 23 15 17" src="https://github.com/janoamaral/tokyo-night-tmux/assets/12657846/f57a29a8-d790-48ac-8c0b-d80c28b90db9">

**Environment:**
- OS: MacOS with M1 chip
- terminal: iTerm2
- tmux version: 3.4
- tokyo-night-tmux branch: all after d3d484e9bcfa22d4202f15c41d18eca7c58f0405 commit

**Additional context**
Config:
```
# Navigation settings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -sg escape-time 100

# Split in CWD by |,- instead of %, "
bind '-' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"
unbind '"'
unbind '%'

bind r source-file ~/.config/tmux/tmux.conf
set -g @tpm-clean 'u' 

# Numbering everything from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'janoamaral/tokyo-night-tmux'
set -g @plugin 'xamut/tmux-spotify'

set -g @tokyo-night-tmux_window_id_style none
set -g @tokyo-night-tmux_show_music 1

run '~/.config/tmux/plugins/tpm/tpm'
```

**Comment by janoamaral** [comment]
Hi, what Bash version are you using?

**Comment by mtk3d** [comment]
Hi, my installed bash version is 3.2.57 (arm64-apple-darwin23)

**Comment by mtk3d** [comment]
Ok, that was probably the problem, I've installed newest bash version using brew and it's working fine now. Thanks for your help!

**Comment by mtk3d** [comment]
Ok, I see there is a new [MacOS](https://github.com/janoamaral/tokyo-night-tmux?tab=readme-ov-file#macos) section in readme. It wasn't there when I installed theme for the first time, and I had updated it from TPM, so I didn't realised that I don't have all required dependencies 😄. Right now after installing all those things it works well, thank you once again!
