### ISSUE TITLE
Detect if device has a battery

### ISSUE THREAD

**Issue by LockeAG** [janoamaral/tokyo-night-tmux#77]
I created a quick solution specifically for Mac users. I also attempted to add solutions for Windows and Linux, but I couldn't test them, so feel free to give them a try. It could be a great addon.

https://github.com/LockeAG/tokyo-night-tmux/blob/master/src/battery-widget.sh

**Comment by janoamaral** [comment]
Hi @LockeAG, please read [how to contribute](https://github.com/janoamaral/tokyo-night-tmux/blob/master/CONTRIBUTING.md) to the project. Could you explain more? I find hard to know exactly what this enhancement do.

**Comment by LockeAG** [comment]
Thank you for the heads-up. I will adhere to the contribution guidelines.

My enhancement addresses a personal preference. Aligning with the trend of using ﻿.dotfiles. Given that I regularly work on both a MacBook and a Mac Desktop, I synchronize my ﻿tmux.conf across these machines for consistency.

The issue arose when the battery widget, enabled on desktop systems, displayed only the percentage, which became a distraction.

To resolve this, I implemented a conditional check within the configuration: if the system has a battery, display the battery status; otherwise, it is empty.

**Comment by janoamaral** [comment]
Yes, it seems fair. Music widget works the same. We should try to make it work in Linux also.
