### ISSUE TITLE
position of window tabs

### ISSUE THREAD

**Issue by nagy135** [janoamaral/tokyo-night-tmux#78]
I would simply like to ask if there is option to move windows bar at least some pixels away from session name, or even make it alight center in entire bar. The way it looks by default makes it quite hard to press correct tab index by just a glance, because it feels like there is extra window (session box)

**Comment by janoamaral** [comment]
Hi! Can you share a screenshot to see the issue?

**Comment by nagy135** [comment]
<img width="567" alt="image" src="https://github.com/janoamaral/tokyo-night-tmux/assets/11056512/31c9fde8-e874-40da-a342-7b9f05d7e5aa">
its not a issue, its feature request. I would love that "server" window to have some spacing from session name left to it. Even move them to the center between widgets on right and session name on the left.

**Comment by janoamaral** [comment]
oh, I see. You can set the position in your config with

`set -g status-justify [left | centre | right]`

i.e. centre

![image](https://github.com/janoamaral/tokyo-night-tmux/assets/10008708/c51e99ae-9858-4b6e-8e43-f7f078d36f9c)

**Comment by nagy135** [comment]
oh, its tmux itself where these separate sections are defined? thanks for explanation !
