### ISSUE TITLE
pane-border-format not showing

### ISSUE THREAD

**Issue by guemidiborhane** [janoamaral/tokyo-night-tmux#81]
**Describe the issue**
the pane-border-format option is only shown briefly then removed

**To Reproduce**
Steps to reproduce the issue:
```tmux
setw -g pane-border-status top
# show current running process in pane title
setw -g pane-border-format " #(ps -f --no-headers --ppid $(tmux display-message -p #{pane_pid}) | awk '{ print substr($0, index($0,$8)) }') "
```

**Environment (please complete the following information):**
- OS: ArchLinux
- terminal: WezTerm
- tmux version: 3.4
- tokyo-night-tmux branch: master

**Comment by guemidiborhane** [comment]
commenting out [this line](https://github.com/janoamaral/tokyo-night-tmux/blob/d34f1487b4a644b13d8b2e9a2ee854ae62cc8d0e/tokyo-night.tmux#L27) seems to fix it

**Comment by janoamaral** [comment]
After carefully check this issue, it's not a bug _per se_, you can add this line at the end of your `.tmux.conf`

```tmux
setw -g pane-border-status top
```

For the time being, the border config is not supported. Feel free to open a discussion to check if the feature is worth working.
