### ISSUE TITLE
Digital font being clipped 

### ISSUE THREAD

**Issue by JustinBacher** [janoamaral/tokyo-night-tmux#82]
When I am using digital as the window or pane id style, and the number is anything visually larger (wider) than 1 it gets clipped by the ui.

<img width="197" alt="image" src="https://github.com/janoamaral/tokyo-night-tmux/assets/32350542/89c4998c-7d56-4553-bda0-3e1180679e51">

---

<img width="252" alt="image" src="https://github.com/janoamaral/tokyo-night-tmux/assets/32350542/6961dce1-b357-4f9e-b445-1b777fd15bf9">

**Environment (please complete the following information):**
- OS: Mac OS Sonoma & Arch/Hyprland (tried on both): 
- terminal: kitty: 
- tmux version: 3.4
- tokyo-night-tmux branch: master
- font: VictorMono Nerd Font

**Comment by janoamaral** [comment]
Maybe I'll need help here. It seems a Mac OS specific bug. This is my setup and can't see any clipping. Please also check the kitty config, check this links:

- https://github.com/kovidgoyal/kitty/issues/6566
- https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.modify_font

![image](https://github.com/janoamaral/tokyo-night-tmux/assets/10008708/ad03fbcb-78ba-4865-876a-31e0c150c567)
