### ISSUE TITLE
Status bar all yellow all of a sudden

### ISSUE THREAD

**Issue by trobrock** [janoamaral/tokyo-night-tmux#85]
**Describe the issue**
I've been using this plugin for about a week without any issues. Then today all of a sudden the background is yellow. I tried digging through the code, but I don't see anywhere that would set the bg to yellow.

**To Reproduce**
Unsure

**Screenshots**
<img width="1512" alt="Screenshot 2024-06-08 at 2 24 10 PM" src="https://github.com/janoamaral/tokyo-night-tmux/assets/94053/202f8a06-d2c8-482f-bae6-e11e82a633ec">

**Environment (please complete the following information):**
- OS: [e.g. Ubuntu 20.04]: Mac OSX
- terminal [e.g. kitty, alacritty]: alacritty
- tmux version [e.g. 3.3a]: 3.4
- tokyo-night-tmux branch [e.g. master, next, legacy]: master

**Comment by trobrock** [comment]
I assume it is, but I cannot figure out what it is. I stripped out everything from tmux conf and still it's yellow.

```tmux.conf
# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"

# run TPM
run '~/.config/tmux/plugins/tpm/tpm'
```

<img width="1512" alt="Screenshot 2024-06-08 at 8 31 52 PM" src="https://github.com/janoamaral/tokyo-night-tmux/assets/94053/0a58b808-f981-461f-a4b1-8c03c4e8129a">

Any suggestions on where to look? I'm not sure if this is normal, but when I source the theme within tmux:
```
$ tmux source ~/.config/tmux/plugins/tokyo-night-tmux/tokyo-night.tmux
/Users/trobrock/.config/tmux/plugins/tokyo-night-tmux/tokyo-night.tmux:10: invalid environment variable
```

**Comment by trobrock** [comment]
Found the issue! It's a bash version issue. I must have uninstalled bash with homebrew.

I was using the system bash 3.2 which clearly didn't support the array variables for the theme. Installing from homebrew and it works again.

**Comment by wzhudev** [comment]
Same here. The built-in of bash on macOS is outdated. I install it with Homebrew and now everything looks good.
