### ISSUE TITLE
Add indicator that pane is zoomed

### ISSUE THREAD

**Issue by destag** [janoamaral/tokyo-night-tmux#97]
**Is your feature request related to a problem? Please describe.**
Sometimes I forget that I zoomed a pane. Its good to have indication when we are zoomed

**Describe the solution you'd like**
Add icon next to window name when it's zoomed.

**Additional context**
![image](https://github.com/janoamaral/tokyo-night-tmux/assets/16159069/7ef64fd8-e6f0-44ce-b4c5-d10121181fe5)

**Comment by k14lb3** [comment]
You can use `tmux set @tokyo-night-tmux_zoom_id_style <style>`.

https://github.com/janoamaral/tokyo-night-tmux/wiki/Windows-Widget#number-styles

**Comment by janoamaral** [comment]
Hi, thanks for your interest in the project. I believe that adding an extra icon will bloat the bar, unless there is a clear necessity of the community for the indicator. Please feel free to open a discussion so anyone can share their use cases.
